language: go
sudo: required
dist: trusty

services:
  - docker

go:
  - 1.6
  - 1.5
install:
  - go get -v golang.org/x/exp/ebnf
  - make build
script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - make test
#  - goveralls -coverprofile=coverage.txt -service=travis-ci
before_install:
  - sudo pip install codecov
after_success:
  codecov
notifications:
  email:
    - tiago.natel@neoway.com.br
